using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraBars.Helpers;
using DevExpress.Skins;
using DevExpress.XtraBars;
using DevExpress.XtraNavBar;
using MySql.Data.MySqlClient;
using RXD.common;
using RXD.pojo;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading;
using System.Runtime.InteropServices;
using NLog;
using DevExpress.XtraCharts;
using DevExpress.XtraBars.Docking2010;
using DevExpress.XtraTreeList;

namespace RXD
{
    public partial class BasicForm : DevExpress.XtraEditors.XtraForm
    {
        [DllImport("convbin.dll", CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl)]
        public static extern int rtklib_convin(int id, int year, int month, int day, int hour);

        [DllImport("rnx2rtkp.dll", CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl)]
        public static extern int rtklib_rnx2rtkp(int year, int month, int day, int hour, int id1, int id, int cycle);

        [DllImport("rnx2rtkp_sky.dll", CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl)]
        public static extern int rtklib_sky(int station, int year, int mon, int day, int hour);

        static AutoResetEvent auto = new AutoResetEvent(false);
        Logger _logger = LogManager.GetCurrentClassLogger();

        public BasicForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        /// <summary>
        /// 工程--创建
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            platformPanel.Visible = true;
            DataPanel.Visible = false;
            refresh_PlatformData();
        }

        /// <summary>
        /// 数据库--修改
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            DBForm db = new DBForm();
            if (db.ShowDialog() == DialogResult.OK)
            {
                db.MdiParent = this;
                db.ShowDialog();
            }
        }

        /// <summary>
        /// 主窗体加载事件
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BasicForm_Load(object sender, EventArgs e)
        {
            // TODO: 这行代码将数据加载到表“rxdDataSet.project”中。您可以根据需要移动或删除它。
            this.projectTableAdapter.Fill(this.rxdDataSet.project);
            // TODO: 这行代码将数据加载到表“rxdDataSet.monitorline”中。您可以根据需要移动或删除它。
            this.monitorlineTableAdapter.Fill(this.rxdDataSet.monitorline);
            // TODO: 这行代码将数据加载到表“rxdDataSet.platform”中。您可以根据需要移动或删除它。
            this.platformTableAdapter.Fill(this.rxdDataSet.platform);
            // TODO: 这行代码将数据加载到表“rxdDataSet.dataview”中。您可以根据需要移动或删除它。
            this.dataviewTableAdapter.Fill(this.rxdDataSet.dataview);
            SkinHelper.InitSkinPopupMenu(MenuSkin);
            //TODO:2注册定时任务
            DateTime now = DateTime.Now.AddHours(1.0);
            DateTime oclock = new DateTime(now.Year, now.Month, now.Day, now.Hour, 0, 0);
            TimeSpan ts = oclock - DateTime.Now;
            timer1.Interval = (int)ts.TotalMilliseconds;
            timer1.Start();

            load_InitData();
        }

        /// <summary>
        /// 项目下拉列表的点击事件
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void itemFaviate_ItemClick(object sender, ItemClickEventArgs e)
        {
            //加载侧边栏数据
            platformPanel.Visible = false;
            DataPanel.Visible = true;
            try
            {
                string sql_project = "select * from project where platform_id = ?";
                MySqlParameter param_platform = new MySqlParameter("@platform_id", MySqlDbType.Int32) { Value = e.Item.Id };
                DataTable dt = common.MySqlHelper.GetDataSet(sql_project, param_platform).Tables[0];
                navBarControl1.Groups.Clear();
                navBarControl1.Controls.Clear();
                this.navBarControl1.View = new DevExpress.XtraNavBar.ViewInfo.StandardSkinExplorerBarViewInfoRegistrator("London Liquid Sky");
                //主窗口标题
                this.Text = e.Item.Caption;
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    //添加Group
                    NavBarGroupControlContainer container = new NavBarGroupControlContainer();
                    navBarControl1.Controls.Add(container);
                    NavBarGroup group = new NavBarGroup();
                    int id = Convert.ToInt32(dt.Rows[i].ItemArray[0]);
                    group.Caption = dt.Rows[i].ItemArray[1].ToString();
                    group.Name = "navBarGroup" + id;
                    group.ControlContainer = container;
                    group.Expanded = true;
                    group.GroupClientHeight = 250;
                    group.GroupStyle = NavBarGroupStyle.ControlContainer;
                    //group.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                    //group.Appearance.Options.UseFont = true;

                    //添加内部navBarControl
                    NavBarControl navBar = new NavBarControl() { Name = "navBar" + i, Text = "navBar" + i };
                    navBar.Dock = DockStyle.Fill;
                    navBar.PaintStyleKind = NavBarViewKind.ExplorerBar;

                    string sql_monitorline = "select * from monitorline where project_id = ?";
                    MySqlParameter param_project = new MySqlParameter("@project_id", MySqlDbType.Int32) { Value = id };
                    DataTable monitorlines = common.MySqlHelper.GetDataSet(sql_monitorline, param_project).Tables[0];
                    for (int j = 0; j < monitorlines.Rows.Count; j++)
                    {
                        int monitorline_id = Convert.ToInt32(monitorlines.Rows[j].ItemArray[0]);
                        NavBarGroup group_inner = new NavBarGroup();
                        group_inner.Caption = monitorlines.Rows[j].ItemArray[1].ToString();
                        group_inner.Name = "navBarGroup_inner" + monitorline_id;
                        group.Expanded = true;
                        //添加item
                        string sql_sensor = "select * from sensor where monitorline_id = ?";
                        MySqlParameter param_monitorline = new MySqlParameter(@"monitorline_id", MySqlDbType.Int32) { Value = monitorline_id };
                        DataTable sensors = common.MySqlHelper.GetDataSet(sql_sensor, param_monitorline).Tables[0];
                        for (int k = 0; k < sensors.Rows.Count; k++)
                        {
                            int sensor_id = Convert.ToInt32(sensors.Rows[k].ItemArray[0]);
                            NavBarItem item = new NavBarItem();
                            item.Name = sensors.Rows[k].ItemArray[1].ToString();
                            item.Caption = sensors.Rows[k].ItemArray[1].ToString();
                            item.Tag = sensor_id;
                            group_inner.ItemLinks.Add(item);
                            item.LinkClicked += new DevExpress.XtraNavBar.NavBarLinkEventHandler(item_LinkClicked);
                        }
                        navBar.Groups.Add(group_inner);
                    }
                    container.Controls.Add(navBar);
                    navBarControl1.Groups.Add(group);
                }
            }
            catch (Exception ex)
            {
                _logger.Trace(ex.Message + "----itemFaviate_ItemClick方法");
            }
        }

        /// <summary>
        /// 切换传感器重新加载数据源
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void item_LinkClicked(object sender, NavBarLinkEventArgs e)
        {
            string sql = "select * from dataview where sensor_id = ?";
            MySqlParameter mp = new MySqlParameter(@"sensor_id", MySqlDbType.Int32) { Value = e.Link.Item.Tag };
            string sql_satallite = "SELECT s1.* FROM sensorinfo s1 LEFT JOIN sensorinfo s2 ON (s1.name = s2.name AND s1.id < s2.id) WHERE s2.id is NULL AND s1.sensor_id = ?";
            //string sql_noise = "SELECT s1.name,s1.noise,s1.type FROM sensorinfo s1 LEFT JOIN sensorinfo s2 ON (s1.name = s2.name AND s1.id < s2.id) WHERE s2.id is NULL AND s1.sensor_id = ?";
            try
            {
                DataSet ds = common.MySqlHelper.GetDataSet(sql, mp);
                this.chartControl1.DataSource = null;
                this.chartControl1.DataSource = ds.Tables[0];

                this.gridControl1.DataSource = null;
                this.gridControl1.DataSource = ds.Tables[0];

                DataSet ds_satallite = common.MySqlHelper.GetDataSet(sql_satallite, mp);
                this.chartControl2.DataSource = null;
                this.chartControl2.DataSource = ds_satallite.Tables[0];

                //DataSet ds_noise = common.MySqlHelper.GetDataSet(sql_noise, mp);
                this.chartControl3.DataSource = null;
                this.chartControl3.DataSource = ds_satallite.Tables[0];
            }
            catch (Exception ex)
            {
                _logger.Trace(ex.Message + "----item_LinkClicked方法");
            }
        }

        /// <summary>
        /// 表格自动行号
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void gridView1_CustomDrawRowIndicator(object sender, DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs e)
        {
            if (e.Info.IsRowIndicator && e.RowHandle >= 0)
            {
                e.Info.DisplayText = (e.RowHandle + 1).ToString();
            }
        }

        /// <summary>
        /// 传感器--创建
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void barButtonItem3_ItemClick(object sender, ItemClickEventArgs e)
        {
            SensorTypeForm sensorTypeForm = new SensorTypeForm();
            if (sensorTypeForm.ShowDialog() == DialogResult.OK)
            {
                sensorTypeForm.MdiParent = this;
                sensorTypeForm.Show();
            }
        }

        /// <summary>
        /// 项目--创建
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void barButtonItem4_ItemClick(object sender, ItemClickEventArgs e)
        {
            LineForm lineForm = new LineForm();
            if (lineForm.ShowDialog() == DialogResult.OK)
            {
                lineForm.MdiParent = this;
                lineForm.Show();
            }
        }

        /// <summary>
        /// 卫星图--传感器点上色
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void chartControl2_BoundDataChanged(object sender, EventArgs e)
        {
            SeriesPointCollection points = chartControl2.Series[0].Points;
            for (int i = 0; i < points.Count; i++)
            {
                if (points[i].ToolTipHint.Equals("G"))
                {
                    points[i].Color = Color.Red;
                    continue;
                }
                if (points[i].ToolTipHint.Equals("C"))
                {
                    points[i].Color = Color.Green;
                    continue;
                }
                if (points[i].ToolTipHint.Equals("R"))
                {
                    points[i].Color = Color.Yellow;
                    continue;
                }
            }
        }

        /// <summary>
        /// 信噪比图--传感器点上色
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void chartControl3_BoundDataChanged(object sender, EventArgs e)
        {
            SeriesPointCollection points = chartControl3.Series[0].Points;
            for (int i = 0; i < points.Count; i++)
            {
                if (points[i].ToolTipHint.Equals("G"))
                {
                    points[i].Color = Color.Red;
                    continue;
                }
                if (points[i].ToolTipHint.Equals("C"))
                {
                    points[i].Color = Color.Green;
                    continue;
                }
                if (points[i].ToolTipHint.Equals("R"))
                {
                    points[i].Color = Color.Yellow;
                    continue;
                }
            }
        }

        /// <summary>
        /// 卫星图和信噪比切换显示
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void windowsUIButtonPanel1_Click(object sender, ButtonEventArgs e)
        {
            switch (e.Button.Properties.Caption)
            {
                case "卫星图":
                    panelControl1.Visible = true;
                    panelControl2.Visible = false;
                    break;
                case "信噪比":
                    panelControl1.Visible = false;
                    panelControl2.Visible = true;
                    break;
                default:
                    break;
            }
        }

        private void timer1_Tick(object sender, EventArgs e)
        {
            timer1.Interval = 3600 * 1000;
            ThreadPool.QueueUserWorkItem(p => { timerToDo(); });
            ThreadPool.QueueUserWorkItem(p =>
            {
                //TODO: 整点重新开启获取数据流的线程
                //Download.GetInstance().ctsToken.Cancel();
                //Download.GetInstance().ctsToken = new CancellationTokenSource();
                Server.GetInstance().ctsToken.Cancel();
                Server.GetInstance().ctsToken = new CancellationTokenSource();
                load_InitData();
            });
        }

        #region 自定义方法
        private void load_InitData()
        {
            //TODO:1开启多线程获取数据流
            //ThreadPool.QueueUserWorkItem(o=> { Download.GetInstance().DownloadData(); });
            ThreadPool.QueueUserWorkItem(o => { Server.GetInstance().Start(); });
            //加载菜单栏项目下拉列表和点击事件
            string sql = "select * from platform";
            DataTable dt = common.MySqlHelper.GetDataSet(sql, null).Tables[0];
            //清空原有子菜单
            barSubItem1.ItemLinks.Clear();
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                BarButtonItem item = new BarButtonItem();
                item.Id = Convert.ToInt32(dt.Rows[i].ItemArray[0]);
                item.Caption = dt.Rows[i].ItemArray[1].ToString();
                item.Name = "itemFaviate" + item.Id;
                item.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(itemFaviate_ItemClick);
                if (i == 0)
                {
                    BarItemLink itemLink = barSubItem1.AddItem(item);
                    itemLink.BeginGroup = true;
                }
                else
                {
                    barSubItem1.AddItem(item);
                }
            }
            //刷新工程和项目下拉框数据源
            refresh_PlatformData();
            refresh_ProjectData();
        }

        public void dat2navFile(int sensor_id, DateTime dt)
        {
            int result = rtklib_convin(sensor_id, dt.Year, dt.Month, dt.Day, dt.Hour);
            Console.WriteLine(result);
        }

        public void nav2posFile(DateTime dt, List<int> idList, int monitorlineid)
        {
            MySqlParameter moniterline_id = new MySqlParameter(@"moniterline_id", MySqlDbType.Int32) { Value = monitorlineid };
            string sql = "select cycles from frequency where monitorline_id = ?";
            DataTable dataTable = common.MySqlHelper.GetDataSet(sql, moniterline_id).Tables[0];
            int result = rtklib_rnx2rtkp(dt.Year, dt.Month, dt.Day, dt.Hour, idList[1], idList[0], Convert.ToInt32(dataTable.Rows[0].ItemArray[0]));
            Console.WriteLine(result);
        }

        private void ReadPosFile(string fileName, int sensor_id)
        {
            try
            {
                fileName += ".pos";
                List<pojo.DataView> SensorList = new List<pojo.DataView>();
                using (FileStream fs = File.OpenRead(fileName))
                {
                    using (StreamReader sr = new StreamReader(fs, Encoding.Default))
                    {
                        string line;
                        while ((line = sr.ReadLine()) != null)
                        {
                            if (line.Contains("%"))
                            {
                                continue;
                            }
                            string[] data = Regex.Split(line, @"\s {2,}");
                            string[] result = new string[4];
                            Array.Copy(data, result, 4);
                            DateTime dt;
                            DateTime.TryParse(result[0], out dt);
                            dt.ToString("yyyy/MM/dd HH:mm:ss");
                            pojo.DataView dataView = new pojo.DataView(double.Parse(result[1]), double.Parse(result[2]), double.Parse(result[3]), dt, sensor_id);
                            SensorList.Add(dataView);
                        }
                    }
                }
                //插入数据库
                //common.MySqlHelper.InsertTable_DataView(SensorList);
                Console.WriteLine("插入数据成功");

                //推送数据到web1.1平台
                string sql_post = "SELECT s.name AS sensorName,ml.name AS monitorLineName,st.name AS sensorType,p.url FROM sensor s LEFT JOIN monitorline ml ON s.monitorline_id = ml.id LEFT JOIN sensortype st ON ml.sensortype_id = st.id LEFT JOIN project p ON ml.project_id = p.id WHERE s.id = ?";
                MySqlParameter param_sensorid = new MySqlParameter(@"id", MySqlDbType.Int32) { Value = sensor_id };
                DataTable table = common.MySqlHelper.GetDataSet(sql_post, param_sensorid).Tables[0];
                if (table.Rows.Count > 0 && SensorList.Count > 0)
                {
                    string sensorName = table.Rows[0].ItemArray[0].ToString();
                    string monitorline = table.Rows[0].ItemArray[1].ToString();
                    string sensorType = table.Rows[0].ItemArray[2].ToString();
                    string url = table.Rows[0].ItemArray[3].ToString();
                    DateTime DateStart = new DateTime(1970, 1, 1, 8, 0, 0);
                    List<SendMsg> SendMsgs = new List<SendMsg>();
                    for (int i = 0; i < SensorList.Count; i++)
                    {
                        SendMsg sendMsg = new SendMsg();
                        sendMsg.deviceData = SensorList[i].X;
                        sendMsg.sinkingData = SensorList[i].Y;
                        sendMsg.sinkingAccumulation = SensorList[i].Z;
                        sendMsg.collectingTime = (SensorList[i].Time - DateStart).TotalMilliseconds.ToString();
                        sendMsg.monitorLineName = monitorline;
                        sendMsg.sensorName = sensorName;
                        sendMsg.sensorType = sensorType;
                        SendMsgs.Add(sendMsg);
                    }
                    Server.GetInstance().SendPost(SendMsgs, url);
                    Console.WriteLine(url);
                }

                //TODO: 6.删除POS文件
                if (File.Exists(fileName))
                {
                    File.Delete(fileName);
                    Console.WriteLine("删除{0}文件成功", fileName);
                }
            }
            catch (Exception ex)
            {
                _logger.Trace(ex.Message + "----ReadPosFile方法");
            }
        }

        private void ReadSkyFile(string fileName, int sensor_id)
        {
            try
            {
                List<pojo.SensorInfo> SensorList = new List<pojo.SensorInfo>();
                using (FileStream fs = File.OpenRead(fileName))
                {
                    using (StreamReader sr = new StreamReader(fs, Encoding.Default))
                    {
                        string line;
                        while ((line = sr.ReadLine()) != null)
                        {
                            string[] data = Regex.Split(line, @",");
                            string[] result = new string[6];
                            Array.Copy(data, result, 6);
                            DateTime dt;
                            DateTime.TryParse(result[5], out dt);
                            dt.ToString("yyyy/MM/dd HH:mm:ss");
                            pojo.SensorInfo sensorInfo = new pojo.SensorInfo(result[0], result[1], double.Parse(result[2]), double.Parse(result[3]), int.Parse(result[4]), dt, sensor_id);
                            SensorList.Add(sensorInfo);
                        }
                    }
                }
                //插入数据库
                //common.MySqlHelper.InsertTable_SensorInfo(SensorList);
                Console.WriteLine("插入数据成功");

                //TODO: 6.删除SKY文件
                if (File.Exists(fileName))
                {
                    File.Delete(fileName);
                    Console.WriteLine("删除{0}文件成功", fileName);
                }
            }
            catch (Exception ex)
            {
                _logger.Trace(ex.Message + "----ReadSkyFile方法");
            }
        }
        
        private int[] getMethodParam(string fileName)
        {
            int[] data = new int[5];
            string[] f1 = Regex.Split(fileName, "-TCPCLIENT-");
            string sensorid = Regex.Split(f1[0], "ReceivedTofile")[1];
            int sensor_id = Convert.ToInt32(sensorid);
            string[] timeStr = f1[1].Split(new char[2] { '_', '-' });
            data[0] = Convert.ToInt32(timeStr[0]);
            data[1] = Convert.ToInt32(timeStr[1]);
            data[2] = Convert.ToInt32(timeStr[2]);
            data[3] = Convert.ToInt32(timeStr[3]);
            data[4] = sensor_id;
            return data;
        }
        
        private void refresh_PlatformData()
        {
            string sql = "select * from platform";
            try
            {
                DataTable dt = common.MySqlHelper.GetDataSet(sql, null).Tables[0];
                gridControl2.DataSource = null;
                gridControl2.DataSource = dt;

                comboBoxEdit1.Properties.Items.Clear();
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    string id = dt.Rows[i].ItemArray[0].ToString();
                    string name = dt.Rows[i].ItemArray[1].ToString();
                    ComboxData comboxData = new ComboxData() { Text = name, Value = id };
                    comboBoxEdit1.Properties.Items.Add(comboxData);
                }
                if (comboBoxEdit1.Properties.Items.Count > 0)
                    comboBoxEdit1.SelectedItem = comboBoxEdit1.Properties.Items[0];
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message + "--refresh_PlatformData");
            }
        }
        
        private void refresh_ProjectData()
        {
            if (comboBoxEdit1.SelectedItem == null)
                return;
            ComboxData comboxData = comboBoxEdit1.SelectedItem as ComboxData;
            int platformid = Convert.ToInt32(comboxData.Value);

            string sql = "SELECT * FROM project p WHERE p.platform_id = ?";
            MySqlParameter mp = new MySqlParameter(@"platform_id", MySqlDbType.Int32) { Value = platformid };
            try
            {
                DataSet ds = common.MySqlHelper.GetDataSet(sql, mp);
                gridControl3.DataSource = null;
                gridControl3.DataSource = ds.Tables[0];
            }
            catch (Exception ex)
            {
                _logger.Trace(ex.Message + "----refresh_ProjectData方法");
            }
        }

        #endregion



        #region 定时核心任务
        private void timerToDo()
        {
            try
            {
                string sql = "select s.id, f.createtime, f.name, s.monitorline_id, s.isbasic from file f left join sensor s on f.sensor_id = s.id where f.states = 0";
                DataTable dt = common.MySqlHelper.GetDataSet(sql, null).Tables[0];
                if (dt.Rows.Count == 0)
                    return;
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    int sensorId = Convert.ToInt32(dt.Rows[i].ItemArray[0]);
                    DateTime createTime = (DateTime)dt.Rows[i].ItemArray[1];
                    string fileName = dt.Rows[i].ItemArray[2].ToString();
                    int monitorLineId = Convert.ToInt32(dt.Rows[i].ItemArray[3]);
                    int isBasic = Convert.ToInt32(dt.Rows[i].ItemArray[4]);
                    if (!File.Exists(fileName + ".DAT"))
                    {
                        continue;
                    }
                    int[] param = getMethodParam(fileName);
                    //TODO: 1.解析DAT文件
                    int result_nav = rtklib_convin(param[4], param[0], param[1], param[2], param[3]);
                    if (result_nav != 0)
                    {
                        _logger.Trace("DAT转NAV文件出错,DAT文件创建时间：{0}, 文件名：{1}", createTime, dt.Rows[i].ItemArray[2].ToString());
                        continue;
                    }
                }
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    int sensorId = Convert.ToInt32(dt.Rows[i].ItemArray[0]);
                    DateTime createTime = (DateTime)dt.Rows[i].ItemArray[1];
                    string fileName = dt.Rows[i].ItemArray[2].ToString();
                    int monitorLineId = Convert.ToInt32(dt.Rows[i].ItemArray[3]);
                    int isBasic = Convert.ToInt32(dt.Rows[i].ItemArray[4]);
                    int basicId;    //基点ID
                    int frequency;  //采集周期
                    //跳过基点
                    if (isBasic == 1)
                    {
                        continue;
                    }
                    if (!File.Exists(fileName + ".nav") && !File.Exists(fileName + ".obs"))
                    {
                        continue;
                    }
                    int[] param = getMethodParam(fileName);
                    string sql_frequency = "select s.id,m.frequency from sensor s left join monitorline m on s.monitorline_id = m.id where m.id = ? and s.isbasic = 1";
                    MySqlParameter moniterline_id = new MySqlParameter(@"moniterline_id", MySqlDbType.Int32) { Value = monitorLineId };
                    DataTable dataTable = common.MySqlHelper.GetDataSet(sql_frequency, moniterline_id).Tables[0];
                    if (dataTable.Rows.Count == 0)
                    {
                        _logger.Trace("周期表没有采集周期的相关记录,monitorlineid:{0}", monitorLineId);
                        continue;
                    }
                    else
                    {
                        basicId = Convert.ToInt32(dataTable.Rows[0].ItemArray[0]);
                        frequency = Convert.ToInt32(dataTable.Rows[0].ItemArray[1]);
                    }
                    //TODO: 2.解析NAV和OBS文件
                    int result_pos = rtklib_rnx2rtkp(param[0], param[1], param[2], param[3], param[4], basicId, frequency);
                    if (result_pos != 0)
                    {
                        _logger.Trace("生成pos文件出错,时间：{0}, 文件名：{1}", DateTime.Now, dt.Rows[0].ItemArray[2].ToString());
                        continue;
                    }
                    //TODO: 3.读取POS文件，批量插入dataview表
                    ReadPosFile(fileName, sensorId);
                }
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    string fileName = dt.Rows[i].ItemArray[2].ToString();
                    if (!File.Exists(@fileName + ".DAT"))
                    {
                        continue;
                    }
                    int[] param = getMethodParam(fileName);

                    string fileName_nav = fileName + ".nav";
                    string fileName_obs = fileName + ".obs";
                    string filename_sky = fileName + ".sky";
                    DateTime time = (DateTime)dt.Rows[i].ItemArray[1];

                    //TODO: 4.生成卫星位置文件
                    int result_sky = rtklib_sky(param[4], param[0], param[1], param[2], param[3]);
                    if (result_sky != 0)
                    {
                        _logger.Trace("生成sky文件出错,时间：{0}, 文件名：{1}", DateTime.Now, fileName);
                        continue;
                    }

                    //TODO: 5.读取卫星信息文件，写入数据库，并删除文件
                    ReadSkyFile(filename_sky, param[4]);

                    //删除NAV和OBS等中间文件
                    if (File.Exists(fileName_nav))
                    {
                        File.Delete(fileName_nav);
                        Console.WriteLine("删除{0}文件成功", fileName_nav);
                    }
                    if (File.Exists(fileName_obs))
                    {
                        File.Delete(fileName_obs);
                        Console.WriteLine("删除{0}文件成功", fileName_obs);
                    }
                    //更新数据库中文件状态
                    string sql_updatefile = "UPDATE file SET states = 1 WHERE name = ? ";
                    MySqlParameter mp = new MySqlParameter(@"name", MySqlDbType.VarChar) { Value = fileName };
                    int result_nav = common.MySqlHelper.ExecuteNonQuery(sql_updatefile, mp);
                    if (result_nav == 1)
                    {
                        Console.WriteLine("更新文件：{0}状态成功", fileName);
                    }
                    else
                    {
                        Console.WriteLine("更新文件：{0}状态失败", fileName);
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.Trace(ex.Message + "----timerToDo方法");
            }
        }
        #endregion

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            //ThreadPool.QueueUserWorkItem(p =>
            //{
            //    //TODO: 整点重新开启获取数据流的线程
            //    //Download.GetInstance().ctsToken.Cancel();
            //    //Download.GetInstance().ctsToken = new CancellationTokenSource();
            //    Server.GetInstance().ctsToken.Cancel();
            //    Server.GetInstance().ctsToken = new CancellationTokenSource();
            //    load_InitData();
            //});
            ThreadPool.QueueUserWorkItem(p => { timerToDo(); });
        }

        private void BasicForm_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (!(XtraMessageBox.Show("真的要退出程序吗？", "退出程序", MessageBoxButtons.OKCancel) == DialogResult.OK))
            {
                e.Cancel = true;
            }
            else
            {
                System.Environment.Exit(0);
            }
        }

        private void PlatformAdd_Click(object sender, EventArgs e)
        {
            PlatformAddForm pAdd = new PlatformAddForm();
            if (pAdd.ShowDialog() == DialogResult.OK)
            {
                pAdd.MdiParent = this;
                pAdd.ShowDialog();
            }
            refresh_PlatformData();
        }

        private void PlatformEdit_Click(object sender, EventArgs e)
        {
            var index = gridView2.GetFocusedDataSourceRowIndex();//获取数据行的索引值，从0开始
            var platformName = gridView2.GetRowCellValue(index, "name");//获取选中行的那个单元格的值
            var platformid = gridView2.GetRowCellValue(index, "id");
            PlatformEditForm pEdit = new PlatformEditForm();
            pEdit.Platformid = Convert.ToInt32(platformid);
            pEdit.PlatformName = platformName.ToString();
            if (pEdit.ShowDialog() == DialogResult.OK)
            {
                pEdit.MdiParent = this;
                pEdit.ShowDialog();
            }
            refresh_PlatformData();
        }

        private void PlatformDel_Click(object sender, EventArgs e)
        {
            if (XtraMessageBox.Show("确定删除所选数据？", "删除提示", MessageBoxButtons.OKCancel, MessageBoxIcon.Question) == DialogResult.OK)
            {
                var index = gridView2.GetFocusedDataSourceRowIndex();//获取数据行的索引值，从0开始
                var id = gridView2.GetRowCellValue(index, "id");
                string sql = "delete from platform where id = ?";
                MySqlParameter param_id = new MySqlParameter(@"id", MySqlDbType.Int32) { Value = Convert.ToInt32(id) };
                int cols = common.MySqlHelper.ExecuteNonQuery(sql, param_id);
                if (cols == 1)
                    alertControl1.Show(this, "提示：", "删除成功");
                else
                    alertControl1.Show(this, "提示：", "删除失败");
                refresh_PlatformData();
            }
        }

        private void projectAdd_Click(object sender, EventArgs e)
        {
            ProjectAddForm pAdd = new ProjectAddForm();
            ComboxData comboxData = comboBoxEdit1.SelectedItem as ComboxData;
            if (comboxData == null)
            {
                XtraMessageBox.Show("请选择工程");
                return;
            }
            pAdd.Platformid = Convert.ToInt32(comboxData.Value);
            pAdd.PlatformName = comboxData.Text;
            if(pAdd.ShowDialog()== DialogResult.OK)
            {
                pAdd.MdiParent = this;
                pAdd.ShowDialog();
            }
            refresh_ProjectData();
        }
        
        private void projectEdit_Click(object sender, EventArgs e)
        {
            ProjectEditForm pEdit = new ProjectEditForm();
            ComboxData comboxData = comboBoxEdit1.SelectedItem as ComboxData;
            if (comboxData == null)
            {
                XtraMessageBox.Show("请选择工程");
                return;
            }
            var index = gridView3.GetFocusedDataSourceRowIndex();
            var id = gridView3.GetRowCellValue(index, "id");
            var name = gridView3.GetRowCellValue(index, "name");
            var url = gridView3.GetRowCellValue(index, "url");
            pEdit.PlatformName = comboxData.Text;
            pEdit.Projectid = Convert.ToInt32(id);
            pEdit.ProjectName = name.ToString();
            pEdit.Url = url.ToString();
            if (pEdit.ShowDialog() == DialogResult.OK)
            {
                pEdit.MdiParent = this;
                pEdit.ShowDialog();
            }
            refresh_ProjectData();
        }

        private void projectDel_Click(object sender, EventArgs e)
        {
            if (XtraMessageBox.Show("确定删除所选数据？", "删除提示", MessageBoxButtons.OKCancel, MessageBoxIcon.Question) == DialogResult.OK)
            {
                var index = gridView3.GetFocusedDataSourceRowIndex();//获取数据行的索引值，从0开始
                var id = gridView3.GetRowCellValue(index, "id");
                string sql = "delete from project where id = ?";
                MySqlParameter param_id = new MySqlParameter(@"id", MySqlDbType.Int32) { Value = Convert.ToInt32(id) };
                int cols = common.MySqlHelper.ExecuteNonQuery(sql, param_id);
                if (cols == 1)
                    alertControl1.Show(this, "提示：", "删除成功");
                else
                    alertControl1.Show(this, "提示：", "删除失败");
                refresh_ProjectData();
            }
        }

        private void comboBoxEdit1_SelectedIndexChanged(object sender, EventArgs e)
        {
            refresh_ProjectData();
        }
    }
}